name: Repo Checker Automation

on:
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 3 * * 1'  

jobs:
  run-repo-checker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install plotly kaleido pandas

      - name: Run all checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python3 run_all_checks.py

      - name: Upload Reports
        uses: actions/upload-artifact@v3
        with:
          name: repo-checker-reports
          path: reports/

